org: naner
service: team-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

functions:
  - ${file(./src/functions/getUser/functions.yml)}
  - ${file(./src/functions/hello/functions.yml)}
  - ${file(./src/functions/createUser/functions.yml)}
