service: team-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    USER_TABLE: 'users'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

custom:
  functionsBasePath: src/functions

functions:
  hello:
    handler: handler.create

  createUser:
    handler: user.create
    memorySize: 128
    description: create user information and starts interview process.
    events:
      - http: 
          path: user
          method: post

  listUsers:
    handler: user.list
    memorySize: 128
    description: List all users
    events:
      - http: 
          path: users
          method: get  

plugins:
  - serverless-functions-base-path
