service: team-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    USER_TABLE: 'users'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

resources:
  Resources:
    CandidatesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: users
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"   
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"

custom:
  functionsBasePath: src/functions

functions:
  imageCreate:
    handler: image.create
  	
  createUser:
    handler: user.create
    memorySize: 128
    description: create user information and starts interview process.
    events:
      - http: 
          path: user
          method: post
  
  listUsers:
    handler: user.list
    memorySize: 128
    description: List all users
    events:
      - http: 
          path: users
          method: get  

plugins:
  - serverless-functions-base-path
